CREATE DATABASE IF NOT EXISTS pkucr_database;
USE pkucr_database;

CREATE TABLE IF NOT EXISTS resources (
    resourceID BIGINT AUTO_INCREMENT PRIMARY KEY,
    courseID BIGINT NOT NULL,
    userID BIGINT NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    uploadTime DATETIME NOT NULL
);
