CREATE DATABASE IF NOT EXISTS pku_database;
USE pku-database;

CREATE TABLE IF NOT EXISTS resources (
    resourceID BIGINT AUTO_INCREMENT PRIMARY KEY,
    courseID VARCHAR(255) NOT NULL,
    userID BIGINT NOT NULL,
    fileName VARCHAR(255) NOT NULL,
    filePath VARCHAR(255) NOT NULL,
    uploadTime DATETIME NOT NULL
);
